# Generated by Django 4.2.16 on 2024-10-06 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '__first__'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=255)),
                ('quantitys', models.IntegerField(default=0)),
                ('taxes', models.IntegerField(default=0)),
                ('observations', models.TextField()),
                ('creation', models.DateTimeField(auto_now=True)),
                ('products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('provider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
        ),
    ]
