# Generated by Django 4.2.16 on 2024-09-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRecibes',
        ),
    ]
