# Generated by Django 4.2.16 on 2024-09-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_sale_product_delete_saleproduct_sale_product'),
        ('orders', '0002_delete_orderrecibes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
