# Generated by Django 4.2.16 on 2024-09-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_provider_added'),
        ('orders', '0003_remove_order_products_delete_productorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
    ]
