# Generated by Django 5.0.6 on 2024-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_added_date_product_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
