# Generated by Django 4.2.16 on 2024-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_sale_product_delete_saleproduct_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
