# Generated by Django 4.2.16 on 2024-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('direction', models.TextField()),
                ('contact', models.TextField()),
                ('provider_status', models.BooleanField(default=True)),
                ('provider_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
