# Generated by Django 4.2.16 on 2024-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
